# Definition of nodes
peer0: &peer0
  addr: localhost:7051
peer1: &peer1
  addr: localhost:8051
peer2: &peer2
  addr: localhost:9051
peer3: &peer3
  addr: localhost:10051

orderer1: &orderer1
  addr: localhost:7050



# Nodes to interact with
endorser_groups: 4
endorsers:
  - *peer0
  - *peer1
  - *peer2
  - *peer3
# we might support multi-committer in the future for more complex test scenario,
# i.e. consider tx committed only if it's done on >50% of nodes. But for now,
# it seems sufficient to support single committer.
committer: *peer1
orderer: *orderer1

# Invocation configs
channel: mychannel
chaincode: smallbank
# args:
#   - GetAllAssets
mspid: Org1MSP
private_key: ./original/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/priv_sk
sign_cert: ./original/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts/User1@org1.example.com-cert.pem
num_of_conn: 8
client_per_conn: 8

check_txid: true
check_rwset: false
