# Definition of nodes
fastpeer: &fastpeer
  addr: localhost:6051
storage: &storage
  addr: localhost:5051
peer0: &peer0
  addr: localhost:7051
peer1: &peer1
  addr: localhost:8051
peer2: &peer2
  addr: localhost:9051
peer3: &peer3
  addr: localhost:10051

orderer1: &orderer1
  addr: localhost:7050

endorser: &endorser
  addr: endorser:7051
local_fastpeer: &local_fastpeer
  addr: fastpeer:7051
local_storage: &local_storage
  addr: storage:7051
local_orderer1: &local_orderer1
  addr: orderer:7050


# Nodes to interact with
endorser_groups: 1
endorsers:
  - *endorser
# we might support multi-committer in the future for more complex test scenario,
# i.e. consider tx committed only if it's done on >50% of nodes. But for now,
# it seems sufficient to support single committer.
committer: *local_storage
orderer: *local_orderer1

# Invocation configs
channel: mychannel
chaincode: smallbank
# args:
#   - GetAllAssets
mspid: Org1MSP
private_key: ./local/peerOrganizations/hlf.com/users/User1@hlf.com/msp/keystore/priv_sk
sign_cert: ./local/peerOrganizations/hlf.com/users/User1@hlf.com/msp/signcerts/User1@hlf.com-cert.pem
num_of_conn: 8
client_per_conn: 8

check_txid: true
check_rwset: false
