# Definition of nodes
peer1: &peer1
  addr: endorser:7051

orderer1: &orderer1
  addr: orderer:7050

# Nodes to interact with
endorserGroupNum: 1
endorsers:
  - *peer1
# we might support multi-committer in the future for more complex test scenario,
# i.e. consider tx committed only if it's done on >50% of nodes. But for now,
# it seems sufficient to support single committer.
committer: *peer1
orderer: *orderer1

# Invocation configs
channel: mychannel
chaincode: smallbank
# args:
#   - GetAllAssets
mspid: Org1MSP
privateKey: ./organizations/peerOrganizations/hlf.com/users/User1@hlf.com/msp/keystore/priv_sk
signCert: ./organizations/peerOrganizations/hlf.com/users/User1@hlf.com/msp/signcerts/User1@hlf.com-cert.pem
connNum: 4
clientPerConnNum: 4

checkTxID: true
checkRWSet: false
